language: swift
osx_image: xcode11.6
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project DateValidator.xcodeproj -scheme DateValidator -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone 7" ONLY_ACTIVE_ARCH=YES